<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Apple MacBook Pro 13-inchA groundbreaki_055942</name>
   <tag></tag>
   <elementGuidId>888a6a59-d7fb-4869-ac46-f7a675e607fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.product-essential</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='product-details-form']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-essential</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Apple MacBook Pro 13-inchA groundbreaking Retina display. A new force-sensing trackpad. All-flash architecture. Powerful dual-core and quad-core Intel processors. Together, these features take the notebook to a new level of performance. And they will do the same for you in everything you create.1 review(s) | Add your reviewManufacturer:  Apple Availability: In stockSKU: AP_MBP_13Free shipping $1,800.00 This product has a minimum quantity of 2Qty:  FacebookTwitterPrintEmailAddThis490ShareWith fifth-generation Intel Core processors, the latest graphics, and faster flash storage, the incredibly advanced MacBook Pro with Retina display moves even further ahead in performance and battery life.* *Compared with the previous generation.Retina display with 2560-by-1600 resolutionFifth-generation dual-core Intel Core i5 processorIntel Iris GraphicsUp to 9 hours of battery life1Faster flash storage2802.11ac Wi-FiTwo Thunderbolt 2 ports for connecting high-performance devices and transferring data at lightning speedTwo USB 3 ports (compatible with USB 2 devices) and HDMIFaceTime HD cameraPages, Numbers, Keynote, iPhoto, iMovie, GarageBand includedOS X, the world's most advanced desktop operating system</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-details-form&quot;)/div[2]/div[@class=&quot;product-essential&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple MacBook Pro 13-inch'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[3]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
